Repository krakenfx/api-go, pull requests merged in 2025-06, with the labels that each got.

#8 feat: enable book method call within book callbacks
  pkg/kraken/book.go
Labels: enhancement, go

#9 feat: remove kraken.Map
  pkg/derivatives/websocket.go
  pkg/kraken/book.go
  pkg/kraken/map.go
Labels: enhancement, go

#10 ci: run code quality and email address checks on all branches
  .github/workflows/code-quality.yml
  .github/workflows/email-check.yml
Labels: enhancement

#11 refactor!: update Futures REST and Spot REST API response handling and request flow
  .github/workflows/code-quality.yml
  .github/workflows/email-check.yml
  examples/futuresrest/batchorder/batchorder.go
  examples/futuresrest/instruments/instruments.go
  examples/futuresrest/openorders/openorders.go
  examples/futuresrest/orderbook/orderbook.go
  examples/futuresrest/ordermgmt/ordermgmt.go
  examples/futuresrest/tickers/tickers.go
  examples/futuresrest/tickersymbol/tickersymbol.go
  examples/futuresrest/tradehistory/tradehistory.go
  examples/futuresrest/unwindqueue/unwindqueue.go
  examples/spotrest/batchmgmt/batchmgmt.go
  examples/spotrest/withdrawmethods/withdrawmethods.go
  pkg/derivatives/assets.go
  pkg/derivatives/entities.go
  pkg/derivatives/rest.go
  pkg/derivatives/restbase.go
  pkg/kraken/kraken.go
  pkg/kraken/mapstruct.go
  pkg/kraken/marshal.go
  pkg/kraken/multipart.go
  pkg/kraken/rest.go
  pkg/spot/rest.go
  pkg/spot/restbase.go
Labels: enhancement, go

#14 feat: add rounding options with banker's rounding as default
  pkg/decimal/decimal.go
  pkg/decimal/decimal_test.go
  pkg/decimal/rounding.go
Labels: enhancement, go

#21 fix: correct spot rest book struct
  .github/workflows/email-check.yml
  .gitignore
  pkg/kraken/book.go
  pkg/spot/entities.go
Labels: bug, go

#23 feat: remove side muxes and prefer incrementing over recounting level quantity
  .github/workflows/email-check.yml
  pkg/book/book.go
  pkg/book/checksum.go
  pkg/book/level.go
  pkg/book/side.go
  pkg/decimal/decimal.go
  pkg/decimal/decimal_test.go
  pkg/spot/books.go
Labels: enhancement, go
